/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_joshuad_mpg123jni_MPG123 */

#ifndef _Included_net_joshuad_mpg123jni_MPG123
#define _Included_net_joshuad_mpg123jni_MPG123
#ifdef __cplusplus
extern "C" {
#endif
#undef net_joshuad_mpg123jni_MPG123_DONE
#define net_joshuad_mpg123jni_MPG123_DONE -12L
#undef net_joshuad_mpg123jni_MPG123_NEW_FORMAT
#define net_joshuad_mpg123jni_MPG123_NEW_FORMAT -11L
#undef net_joshuad_mpg123jni_MPG123_NEED_MORE
#define net_joshuad_mpg123jni_MPG123_NEED_MORE -10L
#undef net_joshuad_mpg123jni_MPG123_ERR
#define net_joshuad_mpg123jni_MPG123_ERR -1L
#undef net_joshuad_mpg123jni_MPG123_OK
#define net_joshuad_mpg123jni_MPG123_OK 0L
#undef net_joshuad_mpg123jni_MPG123_BAD_OUTFORMAT
#define net_joshuad_mpg123jni_MPG123_BAD_OUTFORMAT 1L
#undef net_joshuad_mpg123jni_MPG123_BAD_CHANNEL
#define net_joshuad_mpg123jni_MPG123_BAD_CHANNEL 2L
#undef net_joshuad_mpg123jni_MPG123_BAD_RATE
#define net_joshuad_mpg123jni_MPG123_BAD_RATE 3L
#undef net_joshuad_mpg123jni_MPG123_ERR_16TO8TABLE
#define net_joshuad_mpg123jni_MPG123_ERR_16TO8TABLE 4L
#undef net_joshuad_mpg123jni_MPG123_BAD_PARAM
#define net_joshuad_mpg123jni_MPG123_BAD_PARAM 5L
#undef net_joshuad_mpg123jni_MPG123_BAD_BUFFER
#define net_joshuad_mpg123jni_MPG123_BAD_BUFFER 6L
#undef net_joshuad_mpg123jni_MPG123_OUT_OF_MEM
#define net_joshuad_mpg123jni_MPG123_OUT_OF_MEM 7L
#undef net_joshuad_mpg123jni_MPG123_NOT_INITIALIZED
#define net_joshuad_mpg123jni_MPG123_NOT_INITIALIZED 8L
#undef net_joshuad_mpg123jni_MPG123_BAD_DECODER
#define net_joshuad_mpg123jni_MPG123_BAD_DECODER 9L
#undef net_joshuad_mpg123jni_MPG123_BAD_HANDLE
#define net_joshuad_mpg123jni_MPG123_BAD_HANDLE 10L
#undef net_joshuad_mpg123jni_MPG123_NO_BUFFERS
#define net_joshuad_mpg123jni_MPG123_NO_BUFFERS 11L
#undef net_joshuad_mpg123jni_MPG123_BAD_RVA
#define net_joshuad_mpg123jni_MPG123_BAD_RVA 12L
#undef net_joshuad_mpg123jni_MPG123_NO_GAPLESS
#define net_joshuad_mpg123jni_MPG123_NO_GAPLESS 13L
#undef net_joshuad_mpg123jni_MPG123_NO_SPACE
#define net_joshuad_mpg123jni_MPG123_NO_SPACE 14L
#undef net_joshuad_mpg123jni_MPG123_BAD_TYPES
#define net_joshuad_mpg123jni_MPG123_BAD_TYPES 15L
#undef net_joshuad_mpg123jni_MPG123_BAD_BAND
#define net_joshuad_mpg123jni_MPG123_BAD_BAND 16L
#undef net_joshuad_mpg123jni_MPG123_ERR_NULL
#define net_joshuad_mpg123jni_MPG123_ERR_NULL 17L
#undef net_joshuad_mpg123jni_MPG123_ERR_READER
#define net_joshuad_mpg123jni_MPG123_ERR_READER 18L
#undef net_joshuad_mpg123jni_MPG123_NO_SEEK_FROM_END
#define net_joshuad_mpg123jni_MPG123_NO_SEEK_FROM_END 19L
#undef net_joshuad_mpg123jni_MPG123_BAD_WHENCE
#define net_joshuad_mpg123jni_MPG123_BAD_WHENCE 20L
#undef net_joshuad_mpg123jni_MPG123_NO_TIMEOUT
#define net_joshuad_mpg123jni_MPG123_NO_TIMEOUT 21L
#undef net_joshuad_mpg123jni_MPG123_BAD_FILE
#define net_joshuad_mpg123jni_MPG123_BAD_FILE 22L
#undef net_joshuad_mpg123jni_MPG123_NO_SEEK
#define net_joshuad_mpg123jni_MPG123_NO_SEEK 23L
#undef net_joshuad_mpg123jni_MPG123_NO_READER
#define net_joshuad_mpg123jni_MPG123_NO_READER 24L
#undef net_joshuad_mpg123jni_MPG123_BAD_PARS
#define net_joshuad_mpg123jni_MPG123_BAD_PARS 25L
#undef net_joshuad_mpg123jni_MPG123_BAD_INDEX_PAR
#define net_joshuad_mpg123jni_MPG123_BAD_INDEX_PAR 26L
#undef net_joshuad_mpg123jni_MPG123_OUT_OF_SYNC
#define net_joshuad_mpg123jni_MPG123_OUT_OF_SYNC 27L
#undef net_joshuad_mpg123jni_MPG123_RESYNC_FAIL
#define net_joshuad_mpg123jni_MPG123_RESYNC_FAIL 28L
#undef net_joshuad_mpg123jni_MPG123_NO_8BIT
#define net_joshuad_mpg123jni_MPG123_NO_8BIT 29L
#undef net_joshuad_mpg123jni_MPG123_BAD_ALIGN
#define net_joshuad_mpg123jni_MPG123_BAD_ALIGN 30L
#undef net_joshuad_mpg123jni_MPG123_NULL_BUFFER
#define net_joshuad_mpg123jni_MPG123_NULL_BUFFER 31L
#undef net_joshuad_mpg123jni_MPG123_NO_RELSEEK
#define net_joshuad_mpg123jni_MPG123_NO_RELSEEK 32L
#undef net_joshuad_mpg123jni_MPG123_NULL_POINTER
#define net_joshuad_mpg123jni_MPG123_NULL_POINTER 33L
#undef net_joshuad_mpg123jni_MPG123_BAD_KEY
#define net_joshuad_mpg123jni_MPG123_BAD_KEY 34L
#undef net_joshuad_mpg123jni_MPG123_NO_INDEX
#define net_joshuad_mpg123jni_MPG123_NO_INDEX 35L
#undef net_joshuad_mpg123jni_MPG123_INDEX_FAIL
#define net_joshuad_mpg123jni_MPG123_INDEX_FAIL 36L
#undef net_joshuad_mpg123jni_MPG123_BAD_DECODER_SETUP
#define net_joshuad_mpg123jni_MPG123_BAD_DECODER_SETUP 37L
#undef net_joshuad_mpg123jni_MPG123_MISSING_FEATURE
#define net_joshuad_mpg123jni_MPG123_MISSING_FEATURE 38L
#undef net_joshuad_mpg123jni_MPG123_BAD_VALUE
#define net_joshuad_mpg123jni_MPG123_BAD_VALUE 39L
#undef net_joshuad_mpg123jni_MPG123_LSEEK_FAILED
#define net_joshuad_mpg123jni_MPG123_LSEEK_FAILED 40L
#undef net_joshuad_mpg123jni_MPG123_BAD_CUSTOM_IO
#define net_joshuad_mpg123jni_MPG123_BAD_CUSTOM_IO 41L
#undef net_joshuad_mpg123jni_MPG123_LFS_OVERFLOW
#define net_joshuad_mpg123jni_MPG123_LFS_OVERFLOW 42L
#undef net_joshuad_mpg123jni_MPG123_INT_OVERFLOW
#define net_joshuad_mpg123jni_MPG123_INT_OVERFLOW 43L
/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_mpg123jni_MPG123_init
  (JNIEnv *, jclass);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    makeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_joshuad_mpg123jni_MPG123_makeNew
  (JNIEnv *, jclass);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    openFeed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_joshuad_mpg123jni_MPG123_openFeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    decode
 * Signature: (J[B[B)[I
 */
JNIEXPORT jintArray JNICALL Java_net_joshuad_mpg123jni_MPG123_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    getFormat
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_net_joshuad_mpg123jni_MPG123_getFormat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_joshuad_mpg123jni_MPG123_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    strerror
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_joshuad_mpg123jni_MPG123_strerror
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_joshuad_mpg123jni_MPG123
 * Method:    param
 * Signature: (JIID)V
 */
JNIEXPORT jint JNICALL Java_net_joshuad_mpg123jni_MPG123_param
  (JNIEnv *, jclass, jlong, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
